### ISSUE TITLE
Forbedringsforslag

### ISSUE THREAD

**Issue by ingridberg-spv** [SparebankenVest/nerdschool-introduction-to-web-security#2]
1. fnutt krasjer applikasjonen
2. https://github.com/nerdschoolbergen/introduction-to-web-security/tree/master/exercise-6 - sql spørringen her kunne kanskje vært forklart eller oppgaven brutt ned i enklere deloppgaver. For eksempel var det litt uklart hva sql refererte/hvor det kom fra i GROUP_CONCAT(sql).
Det står "Inspect the source of the voting age". Man kunne kanskje spesifisert page source in the browser.
3. Oppgave 7.2. Her kunne det kanskje vært litt mer forklaring og eksempel på fiks.

**Comment by erlendr** [comment]
Supert 👍 Laget tre nye issues av disse forslagene: #3 , #4, #5 
Lukker denne, så tracker vi de videre i nye issues.
